
paypal:
  client-id: AdaiaDzDPyBEbZW7PS9w2joYQkPNabn9o-86KZDcV8JP0nWj2ieLb7f0BtbW3A1ZhcTn4RoAz1ZybBtZ
  client-secret: EOihc76iScinRyDCFlYw0yu8EZJZkk_8hnbe_1-Vsg8RMpfgDZbkc0YFf_lI1Gy8SiHXPWHg0SLNiim1
  mode: live # Use #sandbox' for testing and 'live' for Production
